/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class R2RMLRuntimeModule extends AbstractR2RMLRuntimeModule {
}
