/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.example.mydsl.R2RMLRuntimeModule;
import org.xtext.example.mydsl.R2RMLStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class R2RMLIdeSetup extends R2RMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new R2RMLRuntimeModule(), new R2RMLIdeModule()));
	}
	
}
