/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.Class#getClassName <em>Class Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getClass_()
 * @model
 * @generated
 */
public interface Class extends EObject
{
  /**
   * Returns the value of the '<em><b>Class Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class Name</em>' containment reference.
   * @see #setClassName(Qname)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getClass_ClassName()
   * @model containment="true"
   * @generated
   */
  Qname getClassName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.Class#getClassName <em>Class Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class Name</em>' containment reference.
   * @see #getClassName()
   * @generated
   */
  void setClassName(Qname value);

} // Class
