/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Constant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.Constant#getConstName <em>Const Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.Constant#getConstStr <em>Const Str</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getConstant()
 * @model
 * @generated
 */
public interface Constant extends EObject
{
  /**
   * Returns the value of the '<em><b>Const Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Name</em>' containment reference.
   * @see #setConstName(iResource)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getConstant_ConstName()
   * @model containment="true"
   * @generated
   */
  iResource getConstName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.Constant#getConstName <em>Const Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Name</em>' containment reference.
   * @see #getConstName()
   * @generated
   */
  void setConstName(iResource value);

  /**
   * Returns the value of the '<em><b>Const Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Const Str</em>' attribute.
   * @see #setConstStr(String)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getConstant_ConstStr()
   * @model
   * @generated
   */
  String getConstStr();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.Constant#getConstStr <em>Const Str</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Const Str</em>' attribute.
   * @see #getConstStr()
   * @generated
   */
  void setConstStr(String value);

} // Constant
