/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>iResource</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.iResource#getUriRef <em>Uri Ref</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.iResource#getQname <em>Qname</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getiResource()
 * @model
 * @generated
 */
public interface iResource extends EObject
{
  /**
   * Returns the value of the '<em><b>Uri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Uri Ref</em>' attribute.
   * @see #setUriRef(String)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getiResource_UriRef()
   * @model
   * @generated
   */
  String getUriRef();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.iResource#getUriRef <em>Uri Ref</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Uri Ref</em>' attribute.
   * @see #getUriRef()
   * @generated
   */
  void setUriRef(String value);

  /**
   * Returns the value of the '<em><b>Qname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qname</em>' containment reference.
   * @see #setQname(Qname)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getiResource_Qname()
   * @model containment="true"
   * @generated
   */
  Qname getQname();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.iResource#getQname <em>Qname</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qname</em>' containment reference.
   * @see #getQname()
   * @generated
   */
  void setQname(Qname value);

} // iResource
