/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Logical Table</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.LogicalTable#getQuery <em>Query</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.LogicalTable#getTableName <em>Table Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getLogicalTable()
 * @model
 * @generated
 */
public interface LogicalTable extends EObject
{
  /**
   * Returns the value of the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Query</em>' containment reference.
   * @see #setQuery(SimpleSelectStatement)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getLogicalTable_Query()
   * @model containment="true"
   * @generated
   */
  SimpleSelectStatement getQuery();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.LogicalTable#getQuery <em>Query</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Query</em>' containment reference.
   * @see #getQuery()
   * @generated
   */
  void setQuery(SimpleSelectStatement value);

  /**
   * Returns the value of the '<em><b>Table Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Name</em>' attribute.
   * @see #setTableName(String)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getLogicalTable_TableName()
   * @model
   * @generated
   */
  String getTableName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.LogicalTable#getTableName <em>Table Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table Name</em>' attribute.
   * @see #getTableName()
   * @generated
   */
  void setTableName(String value);

} // LogicalTable
