/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.ObjectMap#getColumn <em>Column</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.ObjectMap#getTemplate <em>Template</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.ObjectMap#getConstant <em>Constant</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.ObjectMap#getDatatype <em>Datatype</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getObjectMap()
 * @model
 * @generated
 */
public interface ObjectMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column</em>' containment reference.
   * @see #setColumn(Column)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getObjectMap_Column()
   * @model containment="true"
   * @generated
   */
  Column getColumn();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getColumn <em>Column</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column</em>' containment reference.
   * @see #getColumn()
   * @generated
   */
  void setColumn(Column value);

  /**
   * Returns the value of the '<em><b>Template</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Template</em>' containment reference.
   * @see #setTemplate(Template)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getObjectMap_Template()
   * @model containment="true"
   * @generated
   */
  Template getTemplate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getTemplate <em>Template</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Template</em>' containment reference.
   * @see #getTemplate()
   * @generated
   */
  void setTemplate(Template value);

  /**
   * Returns the value of the '<em><b>Constant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Constant</em>' containment reference.
   * @see #setConstant(Constant)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getObjectMap_Constant()
   * @model containment="true"
   * @generated
   */
  Constant getConstant();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getConstant <em>Constant</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Constant</em>' containment reference.
   * @see #getConstant()
   * @generated
   */
  void setConstant(Constant value);

  /**
   * Returns the value of the '<em><b>Datatype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Datatype</em>' containment reference.
   * @see #setDatatype(Datatype)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getObjectMap_Datatype()
   * @model containment="true"
   * @generated
   */
  Datatype getDatatype();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getDatatype <em>Datatype</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Datatype</em>' containment reference.
   * @see #getDatatype()
   * @generated
   */
  void setDatatype(Datatype value);

} // ObjectMap
