/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.Predicate#getPredicateName <em>Predicate Name</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getPredicate()
 * @model
 * @generated
 */
public interface Predicate extends EObject
{
  /**
   * Returns the value of the '<em><b>Predicate Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate Name</em>' containment reference.
   * @see #setPredicateName(Qname)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getPredicate_PredicateName()
   * @model containment="true"
   * @generated
   */
  Qname getPredicateName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.Predicate#getPredicateName <em>Predicate Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate Name</em>' containment reference.
   * @see #getPredicateName()
   * @generated
   */
  void setPredicateName(Qname value);

} // Predicate
