/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Predicate Object Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap#getPredicate <em>Predicate</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap#getObjectMap <em>Object Map</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getPredicateObjectMap()
 * @model
 * @generated
 */
public interface PredicateObjectMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Predicate</em>' containment reference.
   * @see #setPredicate(Predicate)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getPredicateObjectMap_Predicate()
   * @model containment="true"
   * @generated
   */
  Predicate getPredicate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap#getPredicate <em>Predicate</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Predicate</em>' containment reference.
   * @see #getPredicate()
   * @generated
   */
  void setPredicate(Predicate value);

  /**
   * Returns the value of the '<em><b>Object Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object Map</em>' containment reference.
   * @see #setObjectMap(ObjectMap)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getPredicateObjectMap_ObjectMap()
   * @model containment="true"
   * @generated
   */
  ObjectMap getObjectMap();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap#getObjectMap <em>Object Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object Map</em>' containment reference.
   * @see #getObjectMap()
   * @generated
   */
  void setObjectMap(ObjectMap value);

} // PredicateObjectMap
