/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.r2RML.R2RMLFactory
 * @model kind="package"
 * @generated
 */
public interface R2RMLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "r2RML";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/R2RML";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "r2RML";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  R2RMLPackage eINSTANCE = org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.MappingImpl <em>Mapping</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.MappingImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getMapping()
   * @generated
   */
  int MAPPING = 0;

  /**
   * The feature id for the '<em><b>Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING__STATEMENTS = 0;

  /**
   * The number of structural features of the '<em>Mapping</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAPPING_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.StatementImpl <em>Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.StatementImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getStatement()
   * @generated
   */
  int STATEMENT = 1;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__PREFIX = 0;

  /**
   * The feature id for the '<em><b>Triples Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT__TRIPLES_MAP = 1;

  /**
   * The number of structural features of the '<em>Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATEMENT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.PrefixImpl <em>Prefix</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.PrefixImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getPrefix()
   * @generated
   */
  int PREFIX = 2;

  /**
   * The feature id for the '<em><b>Prefix Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX__PREFIX_NAME = 0;

  /**
   * The feature id for the '<em><b>Uri</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX__URI = 1;

  /**
   * The number of structural features of the '<em>Prefix</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREFIX_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.TriplesMapImpl <em>Triples Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.TriplesMapImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getTriplesMap()
   * @generated
   */
  int TRIPLES_MAP = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES_MAP__NAME = 0;

  /**
   * The feature id for the '<em><b>Logical Table</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES_MAP__LOGICAL_TABLE = 1;

  /**
   * The feature id for the '<em><b>Subject Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES_MAP__SUBJECT_MAP = 2;

  /**
   * The feature id for the '<em><b>Predicate Object Maps</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES_MAP__PREDICATE_OBJECT_MAPS = 3;

  /**
   * The number of structural features of the '<em>Triples Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIPLES_MAP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.LogicalTableImpl <em>Logical Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.LogicalTableImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getLogicalTable()
   * @generated
   */
  int LOGICAL_TABLE = 4;

  /**
   * The feature id for the '<em><b>Query</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_TABLE__QUERY = 0;

  /**
   * The feature id for the '<em><b>Table Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_TABLE__TABLE_NAME = 1;

  /**
   * The number of structural features of the '<em>Logical Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOGICAL_TABLE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.SubjectMapImpl <em>Subject Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.SubjectMapImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getSubjectMap()
   * @generated
   */
  int SUBJECT_MAP = 5;

  /**
   * The feature id for the '<em><b>Template</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_MAP__TEMPLATE = 0;

  /**
   * The feature id for the '<em><b>Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_MAP__CLASS = 1;

  /**
   * The number of structural features of the '<em>Subject Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SUBJECT_MAP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.PredicateObjectMapImpl <em>Predicate Object Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.PredicateObjectMapImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getPredicateObjectMap()
   * @generated
   */
  int PREDICATE_OBJECT_MAP = 6;

  /**
   * The feature id for the '<em><b>Predicate</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAP__PREDICATE = 0;

  /**
   * The feature id for the '<em><b>Object Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAP__OBJECT_MAP = 1;

  /**
   * The number of structural features of the '<em>Predicate Object Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_OBJECT_MAP_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.ObjectMapImpl <em>Object Map</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.ObjectMapImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getObjectMap()
   * @generated
   */
  int OBJECT_MAP = 7;

  /**
   * The feature id for the '<em><b>Column</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_MAP__COLUMN = 0;

  /**
   * The feature id for the '<em><b>Template</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_MAP__TEMPLATE = 1;

  /**
   * The feature id for the '<em><b>Constant</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_MAP__CONSTANT = 2;

  /**
   * The feature id for the '<em><b>Datatype</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_MAP__DATATYPE = 3;

  /**
   * The number of structural features of the '<em>Object Map</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OBJECT_MAP_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.ClassImpl <em>Class</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.ClassImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getClass_()
   * @generated
   */
  int CLASS = 8;

  /**
   * The feature id for the '<em><b>Class Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS__CLASS_NAME = 0;

  /**
   * The number of structural features of the '<em>Class</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CLASS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.PredicateImpl <em>Predicate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.PredicateImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getPredicate()
   * @generated
   */
  int PREDICATE = 9;

  /**
   * The feature id for the '<em><b>Predicate Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE__PREDICATE_NAME = 0;

  /**
   * The number of structural features of the '<em>Predicate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PREDICATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.TemplateImpl <em>Template</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.TemplateImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getTemplate()
   * @generated
   */
  int TEMPLATE = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPLATE__NAME = 0;

  /**
   * The number of structural features of the '<em>Template</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEMPLATE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.ColumnImpl <em>Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.ColumnImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getColumn()
   * @generated
   */
  int COLUMN = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN__NAME = 0;

  /**
   * The number of structural features of the '<em>Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.DatatypeImpl <em>Datatype</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.DatatypeImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getDatatype()
   * @generated
   */
  int DATATYPE = 12;

  /**
   * The feature id for the '<em><b>Dt Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE__DT_NAME = 0;

  /**
   * The number of structural features of the '<em>Datatype</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATATYPE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.ConstantImpl <em>Constant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.ConstantImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getConstant()
   * @generated
   */
  int CONSTANT = 13;

  /**
   * The feature id for the '<em><b>Const Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__CONST_NAME = 0;

  /**
   * The feature id for the '<em><b>Const Str</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT__CONST_STR = 1;

  /**
   * The number of structural features of the '<em>Constant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONSTANT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.iResourceImpl <em>iResource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.iResourceImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getiResource()
   * @generated
   */
  int IRESOURCE = 14;

  /**
   * The feature id for the '<em><b>Uri Ref</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRESOURCE__URI_REF = 0;

  /**
   * The feature id for the '<em><b>Qname</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRESOURCE__QNAME = 1;

  /**
   * The number of structural features of the '<em>iResource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IRESOURCE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.NodeIDImpl <em>Node ID</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.NodeIDImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getNodeID()
   * @generated
   */
  int NODE_ID = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_ID__NAME = 0;

  /**
   * The number of structural features of the '<em>Node ID</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NODE_ID_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.QnameImpl <em>Qname</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.QnameImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getQname()
   * @generated
   */
  int QNAME = 16;

  /**
   * The feature id for the '<em><b>Prefix Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QNAME__PREFIX_NAME = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QNAME__NAME = 1;

  /**
   * The number of structural features of the '<em>Qname</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QNAME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl <em>Simple Select Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getSimpleSelectStatement()
   * @generated
   */
  int SIMPLE_SELECT_STATEMENT = 17;

  /**
   * The feature id for the '<em><b>Selected Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS = 0;

  /**
   * The feature id for the '<em><b>Table Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_SELECT_STATEMENT__TABLE_NAME = 1;

  /**
   * The feature id for the '<em><b>Where Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE = 2;

  /**
   * The number of structural features of the '<em>Simple Select Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SIMPLE_SELECT_STATEMENT_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.SelectedColumnsImpl <em>Selected Columns</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.SelectedColumnsImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getSelectedColumns()
   * @generated
   */
  int SELECTED_COLUMNS = 18;

  /**
   * The feature id for the '<em><b>Columns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTED_COLUMNS__COLUMNS = 0;

  /**
   * The number of structural features of the '<em>Selected Columns</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTED_COLUMNS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.WhereClauseImpl <em>Where Clause</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.WhereClauseImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getWhereClause()
   * @generated
   */
  int WHERE_CLAUSE = 19;

  /**
   * The feature id for the '<em><b>Conditions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_CLAUSE__CONDITIONS = 0;

  /**
   * The feature id for the '<em><b>Logic</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_CLAUSE__LOGIC = 1;

  /**
   * The number of structural features of the '<em>Where Clause</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int WHERE_CLAUSE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.ConditionImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 20;

  /**
   * The feature id for the '<em><b>Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__COLUMN = 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__OPERATOR = 1;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__VALUE = 2;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.ValueImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getValue()
   * @generated
   */
  int VALUE = 21;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.BooleanValueImpl <em>Boolean Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.BooleanValueImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getBooleanValue()
   * @generated
   */
  int BOOLEAN_VALUE = 22;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_VALUE__VALUE = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Boolean Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOLEAN_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.NumberValueImpl <em>Number Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.NumberValueImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getNumberValue()
   * @generated
   */
  int NUMBER_VALUE = 23;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_VALUE__VALUE = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Number Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.r2RML.impl.StringValueImpl <em>String Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.r2RML.impl.StringValueImpl
   * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getStringValue()
   * @generated
   */
  int STRING_VALUE = 24;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE__VALUE = VALUE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>String Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_VALUE_FEATURE_COUNT = VALUE_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Mapping <em>Mapping</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Mapping</em>'.
   * @see org.xtext.example.mydsl.r2RML.Mapping
   * @generated
   */
  EClass getMapping();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.r2RML.Mapping#getStatements <em>Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Statements</em>'.
   * @see org.xtext.example.mydsl.r2RML.Mapping#getStatements()
   * @see #getMapping()
   * @generated
   */
  EReference getMapping_Statements();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Statement <em>Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Statement</em>'.
   * @see org.xtext.example.mydsl.r2RML.Statement
   * @generated
   */
  EClass getStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Statement#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Prefix</em>'.
   * @see org.xtext.example.mydsl.r2RML.Statement#getPrefix()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_Prefix();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Statement#getTriplesMap <em>Triples Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Triples Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.Statement#getTriplesMap()
   * @see #getStatement()
   * @generated
   */
  EReference getStatement_TriplesMap();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Prefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Prefix</em>'.
   * @see org.xtext.example.mydsl.r2RML.Prefix
   * @generated
   */
  EClass getPrefix();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Prefix#getPrefixName <em>Prefix Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Prefix#getPrefixName()
   * @see #getPrefix()
   * @generated
   */
  EAttribute getPrefix_PrefixName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Prefix#getUri <em>Uri</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uri</em>'.
   * @see org.xtext.example.mydsl.r2RML.Prefix#getUri()
   * @see #getPrefix()
   * @generated
   */
  EAttribute getPrefix_Uri();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.TriplesMap <em>Triples Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Triples Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.TriplesMap
   * @generated
   */
  EClass getTriplesMap();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.TriplesMap#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.TriplesMap#getName()
   * @see #getTriplesMap()
   * @generated
   */
  EAttribute getTriplesMap_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.TriplesMap#getLogicalTable <em>Logical Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Logical Table</em>'.
   * @see org.xtext.example.mydsl.r2RML.TriplesMap#getLogicalTable()
   * @see #getTriplesMap()
   * @generated
   */
  EReference getTriplesMap_LogicalTable();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.TriplesMap#getSubjectMap <em>Subject Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Subject Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.TriplesMap#getSubjectMap()
   * @see #getTriplesMap()
   * @generated
   */
  EReference getTriplesMap_SubjectMap();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.r2RML.TriplesMap#getPredicateObjectMaps <em>Predicate Object Maps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Predicate Object Maps</em>'.
   * @see org.xtext.example.mydsl.r2RML.TriplesMap#getPredicateObjectMaps()
   * @see #getTriplesMap()
   * @generated
   */
  EReference getTriplesMap_PredicateObjectMaps();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.LogicalTable <em>Logical Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Logical Table</em>'.
   * @see org.xtext.example.mydsl.r2RML.LogicalTable
   * @generated
   */
  EClass getLogicalTable();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.LogicalTable#getQuery <em>Query</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Query</em>'.
   * @see org.xtext.example.mydsl.r2RML.LogicalTable#getQuery()
   * @see #getLogicalTable()
   * @generated
   */
  EReference getLogicalTable_Query();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.LogicalTable#getTableName <em>Table Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.LogicalTable#getTableName()
   * @see #getLogicalTable()
   * @generated
   */
  EAttribute getLogicalTable_TableName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.SubjectMap <em>Subject Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Subject Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.SubjectMap
   * @generated
   */
  EClass getSubjectMap();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.SubjectMap#getTemplate <em>Template</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Template</em>'.
   * @see org.xtext.example.mydsl.r2RML.SubjectMap#getTemplate()
   * @see #getSubjectMap()
   * @generated
   */
  EReference getSubjectMap_Template();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.SubjectMap#getClass_ <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Class</em>'.
   * @see org.xtext.example.mydsl.r2RML.SubjectMap#getClass_()
   * @see #getSubjectMap()
   * @generated
   */
  EReference getSubjectMap_Class();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap <em>Predicate Object Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate Object Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.PredicateObjectMap
   * @generated
   */
  EClass getPredicateObjectMap();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap#getPredicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate</em>'.
   * @see org.xtext.example.mydsl.r2RML.PredicateObjectMap#getPredicate()
   * @see #getPredicateObjectMap()
   * @generated
   */
  EReference getPredicateObjectMap_Predicate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.PredicateObjectMap#getObjectMap <em>Object Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Object Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.PredicateObjectMap#getObjectMap()
   * @see #getPredicateObjectMap()
   * @generated
   */
  EReference getPredicateObjectMap_ObjectMap();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.ObjectMap <em>Object Map</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Object Map</em>'.
   * @see org.xtext.example.mydsl.r2RML.ObjectMap
   * @generated
   */
  EClass getObjectMap();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Column</em>'.
   * @see org.xtext.example.mydsl.r2RML.ObjectMap#getColumn()
   * @see #getObjectMap()
   * @generated
   */
  EReference getObjectMap_Column();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getTemplate <em>Template</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Template</em>'.
   * @see org.xtext.example.mydsl.r2RML.ObjectMap#getTemplate()
   * @see #getObjectMap()
   * @generated
   */
  EReference getObjectMap_Template();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getConstant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Constant</em>'.
   * @see org.xtext.example.mydsl.r2RML.ObjectMap#getConstant()
   * @see #getObjectMap()
   * @generated
   */
  EReference getObjectMap_Constant();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.ObjectMap#getDatatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Datatype</em>'.
   * @see org.xtext.example.mydsl.r2RML.ObjectMap#getDatatype()
   * @see #getObjectMap()
   * @generated
   */
  EReference getObjectMap_Datatype();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Class <em>Class</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Class</em>'.
   * @see org.xtext.example.mydsl.r2RML.Class
   * @generated
   */
  EClass getClass_();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Class#getClassName <em>Class Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Class Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Class#getClassName()
   * @see #getClass_()
   * @generated
   */
  EReference getClass_ClassName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Predicate <em>Predicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Predicate</em>'.
   * @see org.xtext.example.mydsl.r2RML.Predicate
   * @generated
   */
  EClass getPredicate();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Predicate#getPredicateName <em>Predicate Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Predicate Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Predicate#getPredicateName()
   * @see #getPredicate()
   * @generated
   */
  EReference getPredicate_PredicateName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Template <em>Template</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Template</em>'.
   * @see org.xtext.example.mydsl.r2RML.Template
   * @generated
   */
  EClass getTemplate();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Template#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Template#getName()
   * @see #getTemplate()
   * @generated
   */
  EAttribute getTemplate_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Column <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column</em>'.
   * @see org.xtext.example.mydsl.r2RML.Column
   * @generated
   */
  EClass getColumn();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Column#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Column#getName()
   * @see #getColumn()
   * @generated
   */
  EAttribute getColumn_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Datatype <em>Datatype</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datatype</em>'.
   * @see org.xtext.example.mydsl.r2RML.Datatype
   * @generated
   */
  EClass getDatatype();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Datatype#getDtName <em>Dt Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Dt Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Datatype#getDtName()
   * @see #getDatatype()
   * @generated
   */
  EReference getDatatype_DtName();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Constant <em>Constant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Constant</em>'.
   * @see org.xtext.example.mydsl.r2RML.Constant
   * @generated
   */
  EClass getConstant();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Constant#getConstName <em>Const Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Const Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Constant#getConstName()
   * @see #getConstant()
   * @generated
   */
  EReference getConstant_ConstName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Constant#getConstStr <em>Const Str</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Const Str</em>'.
   * @see org.xtext.example.mydsl.r2RML.Constant#getConstStr()
   * @see #getConstant()
   * @generated
   */
  EAttribute getConstant_ConstStr();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.iResource <em>iResource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>iResource</em>'.
   * @see org.xtext.example.mydsl.r2RML.iResource
   * @generated
   */
  EClass getiResource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.iResource#getUriRef <em>Uri Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Uri Ref</em>'.
   * @see org.xtext.example.mydsl.r2RML.iResource#getUriRef()
   * @see #getiResource()
   * @generated
   */
  EAttribute getiResource_UriRef();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.iResource#getQname <em>Qname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Qname</em>'.
   * @see org.xtext.example.mydsl.r2RML.iResource#getQname()
   * @see #getiResource()
   * @generated
   */
  EReference getiResource_Qname();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.NodeID <em>Node ID</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Node ID</em>'.
   * @see org.xtext.example.mydsl.r2RML.NodeID
   * @generated
   */
  EClass getNodeID();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.NodeID#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.NodeID#getName()
   * @see #getNodeID()
   * @generated
   */
  EAttribute getNodeID_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Qname <em>Qname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Qname</em>'.
   * @see org.xtext.example.mydsl.r2RML.Qname
   * @generated
   */
  EClass getQname();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Qname#getPrefixName <em>Prefix Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Qname#getPrefixName()
   * @see #getQname()
   * @generated
   */
  EAttribute getQname_PrefixName();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Qname#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.Qname#getName()
   * @see #getQname()
   * @generated
   */
  EAttribute getQname_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement <em>Simple Select Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Simple Select Statement</em>'.
   * @see org.xtext.example.mydsl.r2RML.SimpleSelectStatement
   * @generated
   */
  EClass getSimpleSelectStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getSelectedColumns <em>Selected Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selected Columns</em>'.
   * @see org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getSelectedColumns()
   * @see #getSimpleSelectStatement()
   * @generated
   */
  EReference getSimpleSelectStatement_SelectedColumns();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getTableName <em>Table Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Table Name</em>'.
   * @see org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getTableName()
   * @see #getSimpleSelectStatement()
   * @generated
   */
  EAttribute getSimpleSelectStatement_TableName();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getWhereClause <em>Where Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Where Clause</em>'.
   * @see org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getWhereClause()
   * @see #getSimpleSelectStatement()
   * @generated
   */
  EReference getSimpleSelectStatement_WhereClause();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.SelectedColumns <em>Selected Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selected Columns</em>'.
   * @see org.xtext.example.mydsl.r2RML.SelectedColumns
   * @generated
   */
  EClass getSelectedColumns();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.r2RML.SelectedColumns#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Columns</em>'.
   * @see org.xtext.example.mydsl.r2RML.SelectedColumns#getColumns()
   * @see #getSelectedColumns()
   * @generated
   */
  EAttribute getSelectedColumns_Columns();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.WhereClause <em>Where Clause</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Where Clause</em>'.
   * @see org.xtext.example.mydsl.r2RML.WhereClause
   * @generated
   */
  EClass getWhereClause();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.r2RML.WhereClause#getConditions <em>Conditions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Conditions</em>'.
   * @see org.xtext.example.mydsl.r2RML.WhereClause#getConditions()
   * @see #getWhereClause()
   * @generated
   */
  EReference getWhereClause_Conditions();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.r2RML.WhereClause#getLogic <em>Logic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Logic</em>'.
   * @see org.xtext.example.mydsl.r2RML.WhereClause#getLogic()
   * @see #getWhereClause()
   * @generated
   */
  EAttribute getWhereClause_Logic();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see org.xtext.example.mydsl.r2RML.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Condition#getColumn <em>Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column</em>'.
   * @see org.xtext.example.mydsl.r2RML.Condition#getColumn()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Column();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.Condition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Operator</em>'.
   * @see org.xtext.example.mydsl.r2RML.Condition#getOperator()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Operator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.r2RML.Condition#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.Condition#getValue()
   * @see #getCondition()
   * @generated
   */
  EReference getCondition_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.BooleanValue <em>Boolean Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Boolean Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.BooleanValue
   * @generated
   */
  EClass getBooleanValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.BooleanValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.BooleanValue#getValue()
   * @see #getBooleanValue()
   * @generated
   */
  EAttribute getBooleanValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.NumberValue <em>Number Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.NumberValue
   * @generated
   */
  EClass getNumberValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.NumberValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.NumberValue#getValue()
   * @see #getNumberValue()
   * @generated
   */
  EAttribute getNumberValue_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.r2RML.StringValue <em>String Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.StringValue
   * @generated
   */
  EClass getStringValue();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.r2RML.StringValue#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.r2RML.StringValue#getValue()
   * @see #getStringValue()
   * @generated
   */
  EAttribute getStringValue_Value();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  R2RMLFactory getR2RMLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.MappingImpl <em>Mapping</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.MappingImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getMapping()
     * @generated
     */
    EClass MAPPING = eINSTANCE.getMapping();

    /**
     * The meta object literal for the '<em><b>Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAPPING__STATEMENTS = eINSTANCE.getMapping_Statements();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.StatementImpl <em>Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.StatementImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getStatement()
     * @generated
     */
    EClass STATEMENT = eINSTANCE.getStatement();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__PREFIX = eINSTANCE.getStatement_Prefix();

    /**
     * The meta object literal for the '<em><b>Triples Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATEMENT__TRIPLES_MAP = eINSTANCE.getStatement_TriplesMap();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.PrefixImpl <em>Prefix</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.PrefixImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getPrefix()
     * @generated
     */
    EClass PREFIX = eINSTANCE.getPrefix();

    /**
     * The meta object literal for the '<em><b>Prefix Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX__PREFIX_NAME = eINSTANCE.getPrefix_PrefixName();

    /**
     * The meta object literal for the '<em><b>Uri</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PREFIX__URI = eINSTANCE.getPrefix_Uri();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.TriplesMapImpl <em>Triples Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.TriplesMapImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getTriplesMap()
     * @generated
     */
    EClass TRIPLES_MAP = eINSTANCE.getTriplesMap();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIPLES_MAP__NAME = eINSTANCE.getTriplesMap_Name();

    /**
     * The meta object literal for the '<em><b>Logical Table</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIPLES_MAP__LOGICAL_TABLE = eINSTANCE.getTriplesMap_LogicalTable();

    /**
     * The meta object literal for the '<em><b>Subject Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIPLES_MAP__SUBJECT_MAP = eINSTANCE.getTriplesMap_SubjectMap();

    /**
     * The meta object literal for the '<em><b>Predicate Object Maps</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRIPLES_MAP__PREDICATE_OBJECT_MAPS = eINSTANCE.getTriplesMap_PredicateObjectMaps();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.LogicalTableImpl <em>Logical Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.LogicalTableImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getLogicalTable()
     * @generated
     */
    EClass LOGICAL_TABLE = eINSTANCE.getLogicalTable();

    /**
     * The meta object literal for the '<em><b>Query</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LOGICAL_TABLE__QUERY = eINSTANCE.getLogicalTable_Query();

    /**
     * The meta object literal for the '<em><b>Table Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute LOGICAL_TABLE__TABLE_NAME = eINSTANCE.getLogicalTable_TableName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.SubjectMapImpl <em>Subject Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.SubjectMapImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getSubjectMap()
     * @generated
     */
    EClass SUBJECT_MAP = eINSTANCE.getSubjectMap();

    /**
     * The meta object literal for the '<em><b>Template</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECT_MAP__TEMPLATE = eINSTANCE.getSubjectMap_Template();

    /**
     * The meta object literal for the '<em><b>Class</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SUBJECT_MAP__CLASS = eINSTANCE.getSubjectMap_Class();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.PredicateObjectMapImpl <em>Predicate Object Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.PredicateObjectMapImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getPredicateObjectMap()
     * @generated
     */
    EClass PREDICATE_OBJECT_MAP = eINSTANCE.getPredicateObjectMap();

    /**
     * The meta object literal for the '<em><b>Predicate</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_MAP__PREDICATE = eINSTANCE.getPredicateObjectMap_Predicate();

    /**
     * The meta object literal for the '<em><b>Object Map</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE_OBJECT_MAP__OBJECT_MAP = eINSTANCE.getPredicateObjectMap_ObjectMap();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.ObjectMapImpl <em>Object Map</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.ObjectMapImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getObjectMap()
     * @generated
     */
    EClass OBJECT_MAP = eINSTANCE.getObjectMap();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_MAP__COLUMN = eINSTANCE.getObjectMap_Column();

    /**
     * The meta object literal for the '<em><b>Template</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_MAP__TEMPLATE = eINSTANCE.getObjectMap_Template();

    /**
     * The meta object literal for the '<em><b>Constant</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_MAP__CONSTANT = eINSTANCE.getObjectMap_Constant();

    /**
     * The meta object literal for the '<em><b>Datatype</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OBJECT_MAP__DATATYPE = eINSTANCE.getObjectMap_Datatype();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.ClassImpl <em>Class</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.ClassImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getClass_()
     * @generated
     */
    EClass CLASS = eINSTANCE.getClass_();

    /**
     * The meta object literal for the '<em><b>Class Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CLASS__CLASS_NAME = eINSTANCE.getClass_ClassName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.PredicateImpl <em>Predicate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.PredicateImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getPredicate()
     * @generated
     */
    EClass PREDICATE = eINSTANCE.getPredicate();

    /**
     * The meta object literal for the '<em><b>Predicate Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PREDICATE__PREDICATE_NAME = eINSTANCE.getPredicate_PredicateName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.TemplateImpl <em>Template</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.TemplateImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getTemplate()
     * @generated
     */
    EClass TEMPLATE = eINSTANCE.getTemplate();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEMPLATE__NAME = eINSTANCE.getTemplate_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.ColumnImpl <em>Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.ColumnImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getColumn()
     * @generated
     */
    EClass COLUMN = eINSTANCE.getColumn();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN__NAME = eINSTANCE.getColumn_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.DatatypeImpl <em>Datatype</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.DatatypeImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getDatatype()
     * @generated
     */
    EClass DATATYPE = eINSTANCE.getDatatype();

    /**
     * The meta object literal for the '<em><b>Dt Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATATYPE__DT_NAME = eINSTANCE.getDatatype_DtName();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.ConstantImpl <em>Constant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.ConstantImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getConstant()
     * @generated
     */
    EClass CONSTANT = eINSTANCE.getConstant();

    /**
     * The meta object literal for the '<em><b>Const Name</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONSTANT__CONST_NAME = eINSTANCE.getConstant_ConstName();

    /**
     * The meta object literal for the '<em><b>Const Str</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONSTANT__CONST_STR = eINSTANCE.getConstant_ConstStr();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.iResourceImpl <em>iResource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.iResourceImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getiResource()
     * @generated
     */
    EClass IRESOURCE = eINSTANCE.getiResource();

    /**
     * The meta object literal for the '<em><b>Uri Ref</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute IRESOURCE__URI_REF = eINSTANCE.getiResource_UriRef();

    /**
     * The meta object literal for the '<em><b>Qname</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IRESOURCE__QNAME = eINSTANCE.getiResource_Qname();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.NodeIDImpl <em>Node ID</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.NodeIDImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getNodeID()
     * @generated
     */
    EClass NODE_ID = eINSTANCE.getNodeID();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NODE_ID__NAME = eINSTANCE.getNodeID_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.QnameImpl <em>Qname</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.QnameImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getQname()
     * @generated
     */
    EClass QNAME = eINSTANCE.getQname();

    /**
     * The meta object literal for the '<em><b>Prefix Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QNAME__PREFIX_NAME = eINSTANCE.getQname_PrefixName();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QNAME__NAME = eINSTANCE.getQname_Name();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl <em>Simple Select Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getSimpleSelectStatement()
     * @generated
     */
    EClass SIMPLE_SELECT_STATEMENT = eINSTANCE.getSimpleSelectStatement();

    /**
     * The meta object literal for the '<em><b>Selected Columns</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS = eINSTANCE.getSimpleSelectStatement_SelectedColumns();

    /**
     * The meta object literal for the '<em><b>Table Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SIMPLE_SELECT_STATEMENT__TABLE_NAME = eINSTANCE.getSimpleSelectStatement_TableName();

    /**
     * The meta object literal for the '<em><b>Where Clause</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE = eINSTANCE.getSimpleSelectStatement_WhereClause();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.SelectedColumnsImpl <em>Selected Columns</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.SelectedColumnsImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getSelectedColumns()
     * @generated
     */
    EClass SELECTED_COLUMNS = eINSTANCE.getSelectedColumns();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTED_COLUMNS__COLUMNS = eINSTANCE.getSelectedColumns_Columns();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.WhereClauseImpl <em>Where Clause</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.WhereClauseImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getWhereClause()
     * @generated
     */
    EClass WHERE_CLAUSE = eINSTANCE.getWhereClause();

    /**
     * The meta object literal for the '<em><b>Conditions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference WHERE_CLAUSE__CONDITIONS = eINSTANCE.getWhereClause_Conditions();

    /**
     * The meta object literal for the '<em><b>Logic</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute WHERE_CLAUSE__LOGIC = eINSTANCE.getWhereClause_Logic();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.ConditionImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__COLUMN = eINSTANCE.getCondition_Column();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__OPERATOR = eINSTANCE.getCondition_Operator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDITION__VALUE = eINSTANCE.getCondition_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.ValueImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.BooleanValueImpl <em>Boolean Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.BooleanValueImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getBooleanValue()
     * @generated
     */
    EClass BOOLEAN_VALUE = eINSTANCE.getBooleanValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOLEAN_VALUE__VALUE = eINSTANCE.getBooleanValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.NumberValueImpl <em>Number Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.NumberValueImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getNumberValue()
     * @generated
     */
    EClass NUMBER_VALUE = eINSTANCE.getNumberValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_VALUE__VALUE = eINSTANCE.getNumberValue_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.r2RML.impl.StringValueImpl <em>String Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.r2RML.impl.StringValueImpl
     * @see org.xtext.example.mydsl.r2RML.impl.R2RMLPackageImpl#getStringValue()
     * @generated
     */
    EClass STRING_VALUE = eINSTANCE.getStringValue();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_VALUE__VALUE = eINSTANCE.getStringValue_Value();

  }

} //R2RMLPackage
