/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Select Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getSelectedColumns <em>Selected Columns</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getTableName <em>Table Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getWhereClause <em>Where Clause</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSimpleSelectStatement()
 * @model
 * @generated
 */
public interface SimpleSelectStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Selected Columns</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selected Columns</em>' containment reference.
   * @see #setSelectedColumns(SelectedColumns)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSimpleSelectStatement_SelectedColumns()
   * @model containment="true"
   * @generated
   */
  SelectedColumns getSelectedColumns();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getSelectedColumns <em>Selected Columns</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selected Columns</em>' containment reference.
   * @see #getSelectedColumns()
   * @generated
   */
  void setSelectedColumns(SelectedColumns value);

  /**
   * Returns the value of the '<em><b>Table Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table Name</em>' attribute.
   * @see #setTableName(String)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSimpleSelectStatement_TableName()
   * @model
   * @generated
   */
  String getTableName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getTableName <em>Table Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table Name</em>' attribute.
   * @see #getTableName()
   * @generated
   */
  void setTableName(String value);

  /**
   * Returns the value of the '<em><b>Where Clause</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where Clause</em>' containment reference.
   * @see #setWhereClause(WhereClause)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSimpleSelectStatement_WhereClause()
   * @model containment="true"
   * @generated
   */
  WhereClause getWhereClause();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.SimpleSelectStatement#getWhereClause <em>Where Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where Clause</em>' containment reference.
   * @see #getWhereClause()
   * @generated
   */
  void setWhereClause(WhereClause value);

} // SimpleSelectStatement
