/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.Statement#getPrefix <em>Prefix</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.Statement#getTriplesMap <em>Triples Map</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
  /**
   * Returns the value of the '<em><b>Prefix</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Prefix</em>' containment reference.
   * @see #setPrefix(Prefix)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getStatement_Prefix()
   * @model containment="true"
   * @generated
   */
  Prefix getPrefix();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.Statement#getPrefix <em>Prefix</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Prefix</em>' containment reference.
   * @see #getPrefix()
   * @generated
   */
  void setPrefix(Prefix value);

  /**
   * Returns the value of the '<em><b>Triples Map</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Triples Map</em>' containment reference.
   * @see #setTriplesMap(TriplesMap)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getStatement_TriplesMap()
   * @model containment="true"
   * @generated
   */
  TriplesMap getTriplesMap();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.Statement#getTriplesMap <em>Triples Map</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Triples Map</em>' containment reference.
   * @see #getTriplesMap()
   * @generated
   */
  void setTriplesMap(TriplesMap value);

} // Statement
