/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Subject Map</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.SubjectMap#getTemplate <em>Template</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.SubjectMap#getClass_ <em>Class</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSubjectMap()
 * @model
 * @generated
 */
public interface SubjectMap extends EObject
{
  /**
   * Returns the value of the '<em><b>Template</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Template</em>' containment reference.
   * @see #setTemplate(Template)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSubjectMap_Template()
   * @model containment="true"
   * @generated
   */
  Template getTemplate();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.SubjectMap#getTemplate <em>Template</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Template</em>' containment reference.
   * @see #getTemplate()
   * @generated
   */
  void setTemplate(Template value);

  /**
   * Returns the value of the '<em><b>Class</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Class</em>' containment reference.
   * @see #setClass(org.xtext.example.mydsl.r2RML.Class)
   * @see org.xtext.example.mydsl.r2RML.R2RMLPackage#getSubjectMap_Class()
   * @model containment="true"
   * @generated
   */
  org.xtext.example.mydsl.r2RML.Class getClass_();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.r2RML.SubjectMap#getClass_ <em>Class</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Class</em>' containment reference.
   * @see #getClass_()
   * @generated
   */
  void setClass(org.xtext.example.mydsl.r2RML.Class value);

} // SubjectMap
