/*
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractR2RMLScopeProvider extends DelegatingScopeProvider {
}
