/**
 * generated by Xtext 2.33.0
 */
package org.xtext.example.mydsl.r2RML.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.r2RML.R2RMLPackage;
import org.xtext.example.mydsl.r2RML.SelectedColumns;
import org.xtext.example.mydsl.r2RML.SimpleSelectStatement;
import org.xtext.example.mydsl.r2RML.WhereClause;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Select Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl#getSelectedColumns <em>Selected Columns</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl#getTableName <em>Table Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.r2RML.impl.SimpleSelectStatementImpl#getWhereClause <em>Where Clause</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SimpleSelectStatementImpl extends MinimalEObjectImpl.Container implements SimpleSelectStatement
{
  /**
   * The cached value of the '{@link #getSelectedColumns() <em>Selected Columns</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSelectedColumns()
   * @generated
   * @ordered
   */
  protected SelectedColumns selectedColumns;

  /**
   * The default value of the '{@link #getTableName() <em>Table Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTableName()
   * @generated
   * @ordered
   */
  protected static final String TABLE_NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTableName() <em>Table Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTableName()
   * @generated
   * @ordered
   */
  protected String tableName = TABLE_NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getWhereClause() <em>Where Clause</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWhereClause()
   * @generated
   * @ordered
   */
  protected WhereClause whereClause;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleSelectStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return R2RMLPackage.Literals.SIMPLE_SELECT_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SelectedColumns getSelectedColumns()
  {
    return selectedColumns;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetSelectedColumns(SelectedColumns newSelectedColumns, NotificationChain msgs)
  {
    SelectedColumns oldSelectedColumns = selectedColumns;
    selectedColumns = newSelectedColumns;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS, oldSelectedColumns, newSelectedColumns);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSelectedColumns(SelectedColumns newSelectedColumns)
  {
    if (newSelectedColumns != selectedColumns)
    {
      NotificationChain msgs = null;
      if (selectedColumns != null)
        msgs = ((InternalEObject)selectedColumns).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS, null, msgs);
      if (newSelectedColumns != null)
        msgs = ((InternalEObject)newSelectedColumns).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS, null, msgs);
      msgs = basicSetSelectedColumns(newSelectedColumns, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS, newSelectedColumns, newSelectedColumns));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTableName()
  {
    return tableName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTableName(String newTableName)
  {
    String oldTableName = tableName;
    tableName = newTableName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, R2RMLPackage.SIMPLE_SELECT_STATEMENT__TABLE_NAME, oldTableName, tableName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public WhereClause getWhereClause()
  {
    return whereClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetWhereClause(WhereClause newWhereClause, NotificationChain msgs)
  {
    WhereClause oldWhereClause = whereClause;
    whereClause = newWhereClause;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE, oldWhereClause, newWhereClause);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setWhereClause(WhereClause newWhereClause)
  {
    if (newWhereClause != whereClause)
    {
      NotificationChain msgs = null;
      if (whereClause != null)
        msgs = ((InternalEObject)whereClause).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE, null, msgs);
      if (newWhereClause != null)
        msgs = ((InternalEObject)newWhereClause).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE, null, msgs);
      msgs = basicSetWhereClause(newWhereClause, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE, newWhereClause, newWhereClause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS:
        return basicSetSelectedColumns(null, msgs);
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE:
        return basicSetWhereClause(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS:
        return getSelectedColumns();
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__TABLE_NAME:
        return getTableName();
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE:
        return getWhereClause();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS:
        setSelectedColumns((SelectedColumns)newValue);
        return;
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__TABLE_NAME:
        setTableName((String)newValue);
        return;
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE:
        setWhereClause((WhereClause)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS:
        setSelectedColumns((SelectedColumns)null);
        return;
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__TABLE_NAME:
        setTableName(TABLE_NAME_EDEFAULT);
        return;
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE:
        setWhereClause((WhereClause)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__SELECTED_COLUMNS:
        return selectedColumns != null;
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__TABLE_NAME:
        return TABLE_NAME_EDEFAULT == null ? tableName != null : !TABLE_NAME_EDEFAULT.equals(tableName);
      case R2RMLPackage.SIMPLE_SELECT_STATEMENT__WHERE_CLAUSE:
        return whereClause != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (tableName: ");
    result.append(tableName);
    result.append(')');
    return result.toString();
  }

} //SimpleSelectStatementImpl
